#/usr/bin/bash


# Banner
echo "CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKLC0tLiAgICwtLS4sLS0uICAgLC0tLiAgICAsLS0tLS0uICAgLC0tLS4gICwtLS0tLS0uICwtLS4gICAsLS0uLC0tLiAgICwtLS4gICAgICAgLC0tLS0tLS4gICAsLS0tLS0uICwtLS0tLS0tLS4sLS0tLS0tLiwtLS4sLS0uICAgLC0tLS0tLS4gLC0tLS4gICAgICAgICAgICAgICAgICAgICAgICAgICAgCnwgICBgLicgICB8IFwgIGAuJyAgLyAgICAgfCAgfCkgL18gJyAgIC4tJyB8ICAuLS0uICd8ICB8ICAgfCAgfHwgICBgLicgICB8LC0tLS0tLnwgIC4tLiAgXCAnICAuLS4gICcnLS0uICAuLS0nfCAgLi0tLSd8ICB8fCAgfCAgIHwgIC4tLS0nJyAgIC4tJyAgICAgICAgICAgICAgICAgICAgICAgICAgIAp8ICB8Jy4nfCAgfCAgJy4gICAgLyAgICAgIHwgIC4tLiAgXGAuICBgLS4gfCAgJy0tJyB8fCAgfC4nLnwgIHx8ICB8Jy4nfCAgfCctLS0tLSd8ICB8ICBcICA6fCAgfCB8ICB8ICAgfCAgfCAgIHwgIGAtLSwgfCAgfHwgIHwgICB8ICBgLS0sIGAuICBgLS4gICAgICAgICAgICAgICAgICAgICAgICAgICAKfCAgfCAgIHwgIHwgICAgfCAgfCAgICAgICB8ICAnLS0nIC8uLScgICAgfHwgIHwgLS0nIHwgICAsJy4gICB8fCAgfCAgIHwgIHwgICAgICAgfCAgJy0tJyAgLycgICctJyAgJyAgIHwgIHwgICB8ICB8YCAgIHwgIHx8ICAnLS0ufCAgYC0tLS4uLScgICAgfCAgICAgICAgICAgICAgICAgICAgICAgICAgCmAtLScgICBgLS0nICAgIGAtLScgICAgICAgYC0tLS0tLScgYC0tLS0tJyBgLS0nICAgICAnLS0nICAgJy0tJ2AtLScgICBgLS0nICAgICAgIGAtLS0tLS0tJyAgYC0tLS0tJyAgICBgLS0nICAgYC0tJyAgICBgLS0nYC0tLS0tJ2AtLS0tLS0nYC0tLS0tJyAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAsLS0tLS0uLC0tLiAgICwtLS4gICAgLC0tLS0tLS4gLC0tLiAsLS0uLC0tLS0tLiAgLC0tLS0tLiAsLS0uICAgLC0tLiAgICAgICAgLC0tLS4gICwtLS4gICAgLC0tLS0tLiAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfCAgfCkgL19cICBgLicgIC8gICAgIHwgIC4tLS4gJ3wgIHwgfCAgfHwgIHwpIC9fIHwgIHwpIC9fIFwgIGAuJyAgLyAgICAgICAgLyAgTyAgXCB8ICB8ICAgJyAgLi0tLi8gCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHwgIC4tLiAgXCcuICAgIC8gICAgICB8ICAnLS0nLid8ICB8IHwgIHx8ICAuLS4gIFx8ICAuLS4gIFwgLicgICAgXCAgICAgICAgfCAgLi0uICB8fCAgfCAgIHwgIHwgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8ICAnLS0nIC8gIHwgIHwgICAgICAgfCAgfFwgIFwgJyAgJy0nICAnfCAgJy0tJyAvfCAgJy0tJyAvLyAgLicuICBcICwtLS0tLnwgIHwgfCAgfHwgICctLS4nICAnLS0nXCAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYC0tLS0tLScgICBgLS0nICAgICAgIGAtLScgJy0tJyBgLS0tLS0nIGAtLS0tLS0nIGAtLS0tLS0nJy0tJyAgICctLScnLS0tLSdgLS0nIGAtLSdgLS0tLS0nIGAtLS0tLScgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK" | base64 -d

# Installing Requirements
sudo apt update
sudo apt install zsh kitty rofi xclip batcat lsd feh picom ranger build-essential git xcb libxcb-util0-dev libxcb-ewmh-dev libxcb-randr0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-xinerama0-dev libasound2-dev libxcb-xtest0-dev libxcb-shape0-dev sudo apt install cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev meson libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev libxcb-glx0-dev -y

# Copying .config files
cp -r .config/* /home/$USER/.config

# Installing HackNerdFonts
sudo cp fonts/* /usr/share/fonts
fc-cache -f -v

# Installing Powerlevel10k
cp -r powerlevel10k ~/powerlevel10k
cp .p10k ~/.p10k

# Copying zsh-config
cp .zshrc ~/.zshrc

# Configuring ranger
ranger --copy-config=all

# Making bspwm
cd bspwm
make
sudo make install
sudo apt update
sudo apt install bspwm -y

# Making sxhkd
cd ..
cd sxhkd
make
sudo apt update
cd ..

# Adding WallPapers to bspwm
cp images/wallpapers/* ~/Images/Wallpapers







